steps:
  # Build the container image from the 'backend' folder
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/dhanti_masala/nodejs-backend-api', './backend']

  # Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/dhanti_masala/nodejs-backend-api']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'nodejs-backend-api'
      - '--image'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/dhanti_masala/nodejs-backend-api'
      - '--region'
      - 'europe-west1'

images:
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/dhanti_masala/nodejs-backend-api'
